package vn.youthmanager.ict.common.db.model;

import java.util.Date;

public class QltnMSpecialized {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qltn_m_specialized.SPECIALIZED_ID
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    private String specializedId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qltn_m_specialized.UNIVERSITY_ID
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    private String universityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qltn_m_specialized.SPECIALIZED_CODE
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    private String specializedCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qltn_m_specialized.SPECIALIZED_NAME
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    private String specializedName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qltn_m_specialized.CREATE_USER_ID
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    private String createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qltn_m_specialized.CREATE_DATE
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qltn_m_specialized.UPDATE_USER_ID
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    private String updateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qltn_m_specialized.LAST_UPDATE_DATE
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    private Date lastUpdateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qltn_m_specialized.DELETE_FLAG
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    private String deleteFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qltn_m_specialized.SPECIALIZED_ID
     *
     * @return the value of qltn_m_specialized.SPECIALIZED_ID
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    public String getSpecializedId() {
        return specializedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qltn_m_specialized.SPECIALIZED_ID
     *
     * @param specializedId the value for qltn_m_specialized.SPECIALIZED_ID
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    public void setSpecializedId(String specializedId) {
        this.specializedId = specializedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qltn_m_specialized.UNIVERSITY_ID
     *
     * @return the value of qltn_m_specialized.UNIVERSITY_ID
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    public String getUniversityId() {
        return universityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qltn_m_specialized.UNIVERSITY_ID
     *
     * @param universityId the value for qltn_m_specialized.UNIVERSITY_ID
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    public void setUniversityId(String universityId) {
        this.universityId = universityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qltn_m_specialized.SPECIALIZED_CODE
     *
     * @return the value of qltn_m_specialized.SPECIALIZED_CODE
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    public String getSpecializedCode() {
        return specializedCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qltn_m_specialized.SPECIALIZED_CODE
     *
     * @param specializedCode the value for qltn_m_specialized.SPECIALIZED_CODE
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    public void setSpecializedCode(String specializedCode) {
        this.specializedCode = specializedCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qltn_m_specialized.SPECIALIZED_NAME
     *
     * @return the value of qltn_m_specialized.SPECIALIZED_NAME
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    public String getSpecializedName() {
        return specializedName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qltn_m_specialized.SPECIALIZED_NAME
     *
     * @param specializedName the value for qltn_m_specialized.SPECIALIZED_NAME
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    public void setSpecializedName(String specializedName) {
        this.specializedName = specializedName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qltn_m_specialized.CREATE_USER_ID
     *
     * @return the value of qltn_m_specialized.CREATE_USER_ID
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qltn_m_specialized.CREATE_USER_ID
     *
     * @param createUserId the value for qltn_m_specialized.CREATE_USER_ID
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qltn_m_specialized.CREATE_DATE
     *
     * @return the value of qltn_m_specialized.CREATE_DATE
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qltn_m_specialized.CREATE_DATE
     *
     * @param createDate the value for qltn_m_specialized.CREATE_DATE
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qltn_m_specialized.UPDATE_USER_ID
     *
     * @return the value of qltn_m_specialized.UPDATE_USER_ID
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    public String getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qltn_m_specialized.UPDATE_USER_ID
     *
     * @param updateUserId the value for qltn_m_specialized.UPDATE_USER_ID
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    public void setUpdateUserId(String updateUserId) {
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qltn_m_specialized.LAST_UPDATE_DATE
     *
     * @return the value of qltn_m_specialized.LAST_UPDATE_DATE
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qltn_m_specialized.LAST_UPDATE_DATE
     *
     * @param lastUpdateDate the value for qltn_m_specialized.LAST_UPDATE_DATE
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qltn_m_specialized.DELETE_FLAG
     *
     * @return the value of qltn_m_specialized.DELETE_FLAG
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    public String getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qltn_m_specialized.DELETE_FLAG
     *
     * @param deleteFlag the value for qltn_m_specialized.DELETE_FLAG
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    public void setDeleteFlag(String deleteFlag) {
        this.deleteFlag = deleteFlag;
    }
}