package vn.youthmanager.ict.common.db.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class QltnMAccessAuthorizationExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table qltn_m_access_authorization
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table qltn_m_access_authorization
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table qltn_m_access_authorization
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_access_authorization
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    public QltnMAccessAuthorizationExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_access_authorization
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_access_authorization
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_access_authorization
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_access_authorization
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_access_authorization
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_access_authorization
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_access_authorization
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_access_authorization
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_access_authorization
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_access_authorization
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table qltn_m_access_authorization
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andAccessAuthorityIdIsNull() {
            addCriterion("ACCESS_AUTHORITY_ID is null");
            return (Criteria) this;
        }

        public Criteria andAccessAuthorityIdIsNotNull() {
            addCriterion("ACCESS_AUTHORITY_ID is not null");
            return (Criteria) this;
        }

        public Criteria andAccessAuthorityIdEqualTo(String value) {
            addCriterion("ACCESS_AUTHORITY_ID =", value, "accessAuthorityId");
            return (Criteria) this;
        }

        public Criteria andAccessAuthorityIdNotEqualTo(String value) {
            addCriterion("ACCESS_AUTHORITY_ID <>", value, "accessAuthorityId");
            return (Criteria) this;
        }

        public Criteria andAccessAuthorityIdGreaterThan(String value) {
            addCriterion("ACCESS_AUTHORITY_ID >", value, "accessAuthorityId");
            return (Criteria) this;
        }

        public Criteria andAccessAuthorityIdGreaterThanOrEqualTo(String value) {
            addCriterion("ACCESS_AUTHORITY_ID >=", value, "accessAuthorityId");
            return (Criteria) this;
        }

        public Criteria andAccessAuthorityIdLessThan(String value) {
            addCriterion("ACCESS_AUTHORITY_ID <", value, "accessAuthorityId");
            return (Criteria) this;
        }

        public Criteria andAccessAuthorityIdLessThanOrEqualTo(String value) {
            addCriterion("ACCESS_AUTHORITY_ID <=", value, "accessAuthorityId");
            return (Criteria) this;
        }

        public Criteria andAccessAuthorityIdLike(String value) {
            addCriterion("ACCESS_AUTHORITY_ID like", value, "accessAuthorityId");
            return (Criteria) this;
        }

        public Criteria andAccessAuthorityIdNotLike(String value) {
            addCriterion("ACCESS_AUTHORITY_ID not like", value, "accessAuthorityId");
            return (Criteria) this;
        }

        public Criteria andAccessAuthorityIdIn(List<String> values) {
            addCriterion("ACCESS_AUTHORITY_ID in", values, "accessAuthorityId");
            return (Criteria) this;
        }

        public Criteria andAccessAuthorityIdNotIn(List<String> values) {
            addCriterion("ACCESS_AUTHORITY_ID not in", values, "accessAuthorityId");
            return (Criteria) this;
        }

        public Criteria andAccessAuthorityIdBetween(String value1, String value2) {
            addCriterion("ACCESS_AUTHORITY_ID between", value1, value2, "accessAuthorityId");
            return (Criteria) this;
        }

        public Criteria andAccessAuthorityIdNotBetween(String value1, String value2) {
            addCriterion("ACCESS_AUTHORITY_ID not between", value1, value2, "accessAuthorityId");
            return (Criteria) this;
        }

        public Criteria andScreenIdIsNull() {
            addCriterion("SCREEN_ID is null");
            return (Criteria) this;
        }

        public Criteria andScreenIdIsNotNull() {
            addCriterion("SCREEN_ID is not null");
            return (Criteria) this;
        }

        public Criteria andScreenIdEqualTo(String value) {
            addCriterion("SCREEN_ID =", value, "screenId");
            return (Criteria) this;
        }

        public Criteria andScreenIdNotEqualTo(String value) {
            addCriterion("SCREEN_ID <>", value, "screenId");
            return (Criteria) this;
        }

        public Criteria andScreenIdGreaterThan(String value) {
            addCriterion("SCREEN_ID >", value, "screenId");
            return (Criteria) this;
        }

        public Criteria andScreenIdGreaterThanOrEqualTo(String value) {
            addCriterion("SCREEN_ID >=", value, "screenId");
            return (Criteria) this;
        }

        public Criteria andScreenIdLessThan(String value) {
            addCriterion("SCREEN_ID <", value, "screenId");
            return (Criteria) this;
        }

        public Criteria andScreenIdLessThanOrEqualTo(String value) {
            addCriterion("SCREEN_ID <=", value, "screenId");
            return (Criteria) this;
        }

        public Criteria andScreenIdLike(String value) {
            addCriterion("SCREEN_ID like", value, "screenId");
            return (Criteria) this;
        }

        public Criteria andScreenIdNotLike(String value) {
            addCriterion("SCREEN_ID not like", value, "screenId");
            return (Criteria) this;
        }

        public Criteria andScreenIdIn(List<String> values) {
            addCriterion("SCREEN_ID in", values, "screenId");
            return (Criteria) this;
        }

        public Criteria andScreenIdNotIn(List<String> values) {
            addCriterion("SCREEN_ID not in", values, "screenId");
            return (Criteria) this;
        }

        public Criteria andScreenIdBetween(String value1, String value2) {
            addCriterion("SCREEN_ID between", value1, value2, "screenId");
            return (Criteria) this;
        }

        public Criteria andScreenIdNotBetween(String value1, String value2) {
            addCriterion("SCREEN_ID not between", value1, value2, "screenId");
            return (Criteria) this;
        }

        public Criteria andScreenDisplayEnableFlagIsNull() {
            addCriterion("SCREEN_DISPLAY_ENABLE_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andScreenDisplayEnableFlagIsNotNull() {
            addCriterion("SCREEN_DISPLAY_ENABLE_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andScreenDisplayEnableFlagEqualTo(Boolean value) {
            addCriterion("SCREEN_DISPLAY_ENABLE_FLAG =", value, "screenDisplayEnableFlag");
            return (Criteria) this;
        }

        public Criteria andScreenDisplayEnableFlagNotEqualTo(Boolean value) {
            addCriterion("SCREEN_DISPLAY_ENABLE_FLAG <>", value, "screenDisplayEnableFlag");
            return (Criteria) this;
        }

        public Criteria andScreenDisplayEnableFlagGreaterThan(Boolean value) {
            addCriterion("SCREEN_DISPLAY_ENABLE_FLAG >", value, "screenDisplayEnableFlag");
            return (Criteria) this;
        }

        public Criteria andScreenDisplayEnableFlagGreaterThanOrEqualTo(Boolean value) {
            addCriterion("SCREEN_DISPLAY_ENABLE_FLAG >=", value, "screenDisplayEnableFlag");
            return (Criteria) this;
        }

        public Criteria andScreenDisplayEnableFlagLessThan(Boolean value) {
            addCriterion("SCREEN_DISPLAY_ENABLE_FLAG <", value, "screenDisplayEnableFlag");
            return (Criteria) this;
        }

        public Criteria andScreenDisplayEnableFlagLessThanOrEqualTo(Boolean value) {
            addCriterion("SCREEN_DISPLAY_ENABLE_FLAG <=", value, "screenDisplayEnableFlag");
            return (Criteria) this;
        }

        public Criteria andScreenDisplayEnableFlagIn(List<Boolean> values) {
            addCriterion("SCREEN_DISPLAY_ENABLE_FLAG in", values, "screenDisplayEnableFlag");
            return (Criteria) this;
        }

        public Criteria andScreenDisplayEnableFlagNotIn(List<Boolean> values) {
            addCriterion("SCREEN_DISPLAY_ENABLE_FLAG not in", values, "screenDisplayEnableFlag");
            return (Criteria) this;
        }

        public Criteria andScreenDisplayEnableFlagBetween(Boolean value1, Boolean value2) {
            addCriterion("SCREEN_DISPLAY_ENABLE_FLAG between", value1, value2, "screenDisplayEnableFlag");
            return (Criteria) this;
        }

        public Criteria andScreenDisplayEnableFlagNotBetween(Boolean value1, Boolean value2) {
            addCriterion("SCREEN_DISPLAY_ENABLE_FLAG not between", value1, value2, "screenDisplayEnableFlag");
            return (Criteria) this;
        }

        public Criteria andAddableFlagIsNull() {
            addCriterion("ADDABLE_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andAddableFlagIsNotNull() {
            addCriterion("ADDABLE_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andAddableFlagEqualTo(Boolean value) {
            addCriterion("ADDABLE_FLAG =", value, "addableFlag");
            return (Criteria) this;
        }

        public Criteria andAddableFlagNotEqualTo(Boolean value) {
            addCriterion("ADDABLE_FLAG <>", value, "addableFlag");
            return (Criteria) this;
        }

        public Criteria andAddableFlagGreaterThan(Boolean value) {
            addCriterion("ADDABLE_FLAG >", value, "addableFlag");
            return (Criteria) this;
        }

        public Criteria andAddableFlagGreaterThanOrEqualTo(Boolean value) {
            addCriterion("ADDABLE_FLAG >=", value, "addableFlag");
            return (Criteria) this;
        }

        public Criteria andAddableFlagLessThan(Boolean value) {
            addCriterion("ADDABLE_FLAG <", value, "addableFlag");
            return (Criteria) this;
        }

        public Criteria andAddableFlagLessThanOrEqualTo(Boolean value) {
            addCriterion("ADDABLE_FLAG <=", value, "addableFlag");
            return (Criteria) this;
        }

        public Criteria andAddableFlagIn(List<Boolean> values) {
            addCriterion("ADDABLE_FLAG in", values, "addableFlag");
            return (Criteria) this;
        }

        public Criteria andAddableFlagNotIn(List<Boolean> values) {
            addCriterion("ADDABLE_FLAG not in", values, "addableFlag");
            return (Criteria) this;
        }

        public Criteria andAddableFlagBetween(Boolean value1, Boolean value2) {
            addCriterion("ADDABLE_FLAG between", value1, value2, "addableFlag");
            return (Criteria) this;
        }

        public Criteria andAddableFlagNotBetween(Boolean value1, Boolean value2) {
            addCriterion("ADDABLE_FLAG not between", value1, value2, "addableFlag");
            return (Criteria) this;
        }

        public Criteria andUpdatableFlagIsNull() {
            addCriterion("UPDATABLE_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andUpdatableFlagIsNotNull() {
            addCriterion("UPDATABLE_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatableFlagEqualTo(Boolean value) {
            addCriterion("UPDATABLE_FLAG =", value, "updatableFlag");
            return (Criteria) this;
        }

        public Criteria andUpdatableFlagNotEqualTo(Boolean value) {
            addCriterion("UPDATABLE_FLAG <>", value, "updatableFlag");
            return (Criteria) this;
        }

        public Criteria andUpdatableFlagGreaterThan(Boolean value) {
            addCriterion("UPDATABLE_FLAG >", value, "updatableFlag");
            return (Criteria) this;
        }

        public Criteria andUpdatableFlagGreaterThanOrEqualTo(Boolean value) {
            addCriterion("UPDATABLE_FLAG >=", value, "updatableFlag");
            return (Criteria) this;
        }

        public Criteria andUpdatableFlagLessThan(Boolean value) {
            addCriterion("UPDATABLE_FLAG <", value, "updatableFlag");
            return (Criteria) this;
        }

        public Criteria andUpdatableFlagLessThanOrEqualTo(Boolean value) {
            addCriterion("UPDATABLE_FLAG <=", value, "updatableFlag");
            return (Criteria) this;
        }

        public Criteria andUpdatableFlagIn(List<Boolean> values) {
            addCriterion("UPDATABLE_FLAG in", values, "updatableFlag");
            return (Criteria) this;
        }

        public Criteria andUpdatableFlagNotIn(List<Boolean> values) {
            addCriterion("UPDATABLE_FLAG not in", values, "updatableFlag");
            return (Criteria) this;
        }

        public Criteria andUpdatableFlagBetween(Boolean value1, Boolean value2) {
            addCriterion("UPDATABLE_FLAG between", value1, value2, "updatableFlag");
            return (Criteria) this;
        }

        public Criteria andUpdatableFlagNotBetween(Boolean value1, Boolean value2) {
            addCriterion("UPDATABLE_FLAG not between", value1, value2, "updatableFlag");
            return (Criteria) this;
        }

        public Criteria andDeletableFlagIsNull() {
            addCriterion("DELETABLE_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andDeletableFlagIsNotNull() {
            addCriterion("DELETABLE_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andDeletableFlagEqualTo(Boolean value) {
            addCriterion("DELETABLE_FLAG =", value, "deletableFlag");
            return (Criteria) this;
        }

        public Criteria andDeletableFlagNotEqualTo(Boolean value) {
            addCriterion("DELETABLE_FLAG <>", value, "deletableFlag");
            return (Criteria) this;
        }

        public Criteria andDeletableFlagGreaterThan(Boolean value) {
            addCriterion("DELETABLE_FLAG >", value, "deletableFlag");
            return (Criteria) this;
        }

        public Criteria andDeletableFlagGreaterThanOrEqualTo(Boolean value) {
            addCriterion("DELETABLE_FLAG >=", value, "deletableFlag");
            return (Criteria) this;
        }

        public Criteria andDeletableFlagLessThan(Boolean value) {
            addCriterion("DELETABLE_FLAG <", value, "deletableFlag");
            return (Criteria) this;
        }

        public Criteria andDeletableFlagLessThanOrEqualTo(Boolean value) {
            addCriterion("DELETABLE_FLAG <=", value, "deletableFlag");
            return (Criteria) this;
        }

        public Criteria andDeletableFlagIn(List<Boolean> values) {
            addCriterion("DELETABLE_FLAG in", values, "deletableFlag");
            return (Criteria) this;
        }

        public Criteria andDeletableFlagNotIn(List<Boolean> values) {
            addCriterion("DELETABLE_FLAG not in", values, "deletableFlag");
            return (Criteria) this;
        }

        public Criteria andDeletableFlagBetween(Boolean value1, Boolean value2) {
            addCriterion("DELETABLE_FLAG between", value1, value2, "deletableFlag");
            return (Criteria) this;
        }

        public Criteria andDeletableFlagNotBetween(Boolean value1, Boolean value2) {
            addCriterion("DELETABLE_FLAG not between", value1, value2, "deletableFlag");
            return (Criteria) this;
        }

        public Criteria andReferenceFlagIsNull() {
            addCriterion("REFERENCE_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andReferenceFlagIsNotNull() {
            addCriterion("REFERENCE_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andReferenceFlagEqualTo(Boolean value) {
            addCriterion("REFERENCE_FLAG =", value, "referenceFlag");
            return (Criteria) this;
        }

        public Criteria andReferenceFlagNotEqualTo(Boolean value) {
            addCriterion("REFERENCE_FLAG <>", value, "referenceFlag");
            return (Criteria) this;
        }

        public Criteria andReferenceFlagGreaterThan(Boolean value) {
            addCriterion("REFERENCE_FLAG >", value, "referenceFlag");
            return (Criteria) this;
        }

        public Criteria andReferenceFlagGreaterThanOrEqualTo(Boolean value) {
            addCriterion("REFERENCE_FLAG >=", value, "referenceFlag");
            return (Criteria) this;
        }

        public Criteria andReferenceFlagLessThan(Boolean value) {
            addCriterion("REFERENCE_FLAG <", value, "referenceFlag");
            return (Criteria) this;
        }

        public Criteria andReferenceFlagLessThanOrEqualTo(Boolean value) {
            addCriterion("REFERENCE_FLAG <=", value, "referenceFlag");
            return (Criteria) this;
        }

        public Criteria andReferenceFlagIn(List<Boolean> values) {
            addCriterion("REFERENCE_FLAG in", values, "referenceFlag");
            return (Criteria) this;
        }

        public Criteria andReferenceFlagNotIn(List<Boolean> values) {
            addCriterion("REFERENCE_FLAG not in", values, "referenceFlag");
            return (Criteria) this;
        }

        public Criteria andReferenceFlagBetween(Boolean value1, Boolean value2) {
            addCriterion("REFERENCE_FLAG between", value1, value2, "referenceFlag");
            return (Criteria) this;
        }

        public Criteria andReferenceFlagNotBetween(Boolean value1, Boolean value2) {
            addCriterion("REFERENCE_FLAG not between", value1, value2, "referenceFlag");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNull() {
            addCriterion("CREATE_USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIsNotNull() {
            addCriterion("CREATE_USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdEqualTo(String value) {
            addCriterion("CREATE_USER_ID =", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotEqualTo(String value) {
            addCriterion("CREATE_USER_ID <>", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThan(String value) {
            addCriterion("CREATE_USER_ID >", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("CREATE_USER_ID >=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThan(String value) {
            addCriterion("CREATE_USER_ID <", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLessThanOrEqualTo(String value) {
            addCriterion("CREATE_USER_ID <=", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdLike(String value) {
            addCriterion("CREATE_USER_ID like", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotLike(String value) {
            addCriterion("CREATE_USER_ID not like", value, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdIn(List<String> values) {
            addCriterion("CREATE_USER_ID in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotIn(List<String> values) {
            addCriterion("CREATE_USER_ID not in", values, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdBetween(String value1, String value2) {
            addCriterion("CREATE_USER_ID between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateUserIdNotBetween(String value1, String value2) {
            addCriterion("CREATE_USER_ID not between", value1, value2, "createUserId");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNull() {
            addCriterion("CREATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andCreateDateIsNotNull() {
            addCriterion("CREATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDateEqualTo(Date value) {
            addCriterion("CREATE_DATE =", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotEqualTo(Date value) {
            addCriterion("CREATE_DATE <>", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThan(Date value) {
            addCriterion("CREATE_DATE >", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATE_DATE >=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThan(Date value) {
            addCriterion("CREATE_DATE <", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateLessThanOrEqualTo(Date value) {
            addCriterion("CREATE_DATE <=", value, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateIn(List<Date> values) {
            addCriterion("CREATE_DATE in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotIn(List<Date> values) {
            addCriterion("CREATE_DATE not in", values, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateBetween(Date value1, Date value2) {
            addCriterion("CREATE_DATE between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andCreateDateNotBetween(Date value1, Date value2) {
            addCriterion("CREATE_DATE not between", value1, value2, "createDate");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNull() {
            addCriterion("UPDATE_USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIsNotNull() {
            addCriterion("UPDATE_USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdEqualTo(String value) {
            addCriterion("UPDATE_USER_ID =", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotEqualTo(String value) {
            addCriterion("UPDATE_USER_ID <>", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThan(String value) {
            addCriterion("UPDATE_USER_ID >", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("UPDATE_USER_ID >=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThan(String value) {
            addCriterion("UPDATE_USER_ID <", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLessThanOrEqualTo(String value) {
            addCriterion("UPDATE_USER_ID <=", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdLike(String value) {
            addCriterion("UPDATE_USER_ID like", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotLike(String value) {
            addCriterion("UPDATE_USER_ID not like", value, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdIn(List<String> values) {
            addCriterion("UPDATE_USER_ID in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotIn(List<String> values) {
            addCriterion("UPDATE_USER_ID not in", values, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdBetween(String value1, String value2) {
            addCriterion("UPDATE_USER_ID between", value1, value2, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIdNotBetween(String value1, String value2) {
            addCriterion("UPDATE_USER_ID not between", value1, value2, "updateUserId");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateIsNull() {
            addCriterion("LAST_UPDATE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateIsNotNull() {
            addCriterion("LAST_UPDATE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateEqualTo(Date value) {
            addCriterion("LAST_UPDATE_DATE =", value, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateNotEqualTo(Date value) {
            addCriterion("LAST_UPDATE_DATE <>", value, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateGreaterThan(Date value) {
            addCriterion("LAST_UPDATE_DATE >", value, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateGreaterThanOrEqualTo(Date value) {
            addCriterion("LAST_UPDATE_DATE >=", value, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateLessThan(Date value) {
            addCriterion("LAST_UPDATE_DATE <", value, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateLessThanOrEqualTo(Date value) {
            addCriterion("LAST_UPDATE_DATE <=", value, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateIn(List<Date> values) {
            addCriterion("LAST_UPDATE_DATE in", values, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateNotIn(List<Date> values) {
            addCriterion("LAST_UPDATE_DATE not in", values, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateBetween(Date value1, Date value2) {
            addCriterion("LAST_UPDATE_DATE between", value1, value2, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andLastUpdateDateNotBetween(Date value1, Date value2) {
            addCriterion("LAST_UPDATE_DATE not between", value1, value2, "lastUpdateDate");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagIsNull() {
            addCriterion("DELETE_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagIsNotNull() {
            addCriterion("DELETE_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagEqualTo(Boolean value) {
            addCriterion("DELETE_FLAG =", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagNotEqualTo(Boolean value) {
            addCriterion("DELETE_FLAG <>", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagGreaterThan(Boolean value) {
            addCriterion("DELETE_FLAG >", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagGreaterThanOrEqualTo(Boolean value) {
            addCriterion("DELETE_FLAG >=", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagLessThan(Boolean value) {
            addCriterion("DELETE_FLAG <", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagLessThanOrEqualTo(Boolean value) {
            addCriterion("DELETE_FLAG <=", value, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagIn(List<Boolean> values) {
            addCriterion("DELETE_FLAG in", values, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagNotIn(List<Boolean> values) {
            addCriterion("DELETE_FLAG not in", values, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagBetween(Boolean value1, Boolean value2) {
            addCriterion("DELETE_FLAG between", value1, value2, "deleteFlag");
            return (Criteria) this;
        }

        public Criteria andDeleteFlagNotBetween(Boolean value1, Boolean value2) {
            addCriterion("DELETE_FLAG not between", value1, value2, "deleteFlag");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table qltn_m_access_authorization
     *
     * @mbggenerated do_not_delete_during_merge Sat Apr 08 18:31:52 ICT 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table qltn_m_access_authorization
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}