package vn.youthmanager.ict.common.db.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import vn.youthmanager.ict.common.db.model.QltnMSpecialized;
import vn.youthmanager.ict.common.db.model.QltnMSpecializedExample;

public interface QltnMSpecializedMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_specialized
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int countByExample(QltnMSpecializedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_specialized
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int deleteByExample(QltnMSpecializedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_specialized
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int deleteByPrimaryKey(String specializedId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_specialized
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int insert(QltnMSpecialized record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_specialized
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int insertSelective(QltnMSpecialized record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_specialized
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    List<QltnMSpecialized> selectByExample(QltnMSpecializedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_specialized
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    QltnMSpecialized selectByPrimaryKey(String specializedId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_specialized
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int updateByExampleSelective(@Param("record") QltnMSpecialized record, @Param("example") QltnMSpecializedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_specialized
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int updateByExample(@Param("record") QltnMSpecialized record, @Param("example") QltnMSpecializedExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_specialized
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int updateByPrimaryKeySelective(QltnMSpecialized record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_specialized
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int updateByPrimaryKey(QltnMSpecialized record);
}