package vn.youthmanager.ict.common.db.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import vn.youthmanager.ict.common.db.model.QltnMNation;
import vn.youthmanager.ict.common.db.model.QltnMNationExample;

public interface QltnMNationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_nation
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int countByExample(QltnMNationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_nation
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int deleteByExample(QltnMNationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_nation
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int deleteByPrimaryKey(String nationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_nation
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int insert(QltnMNation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_nation
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int insertSelective(QltnMNation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_nation
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    List<QltnMNation> selectByExample(QltnMNationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_nation
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    QltnMNation selectByPrimaryKey(String nationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_nation
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int updateByExampleSelective(@Param("record") QltnMNation record, @Param("example") QltnMNationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_nation
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int updateByExample(@Param("record") QltnMNation record, @Param("example") QltnMNationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_nation
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int updateByPrimaryKeySelective(QltnMNation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_nation
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int updateByPrimaryKey(QltnMNation record);
}