package vn.youthmanager.ict.common.db.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import vn.youthmanager.ict.common.db.model.QltnMUniversity;
import vn.youthmanager.ict.common.db.model.QltnMUniversityExample;

public interface QltnMUniversityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_university
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int countByExample(QltnMUniversityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_university
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int deleteByExample(QltnMUniversityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_university
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int deleteByPrimaryKey(String universityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_university
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int insert(QltnMUniversity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_university
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int insertSelective(QltnMUniversity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_university
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    List<QltnMUniversity> selectByExample(QltnMUniversityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_university
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    QltnMUniversity selectByPrimaryKey(String universityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_university
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int updateByExampleSelective(@Param("record") QltnMUniversity record, @Param("example") QltnMUniversityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_university
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int updateByExample(@Param("record") QltnMUniversity record, @Param("example") QltnMUniversityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_university
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int updateByPrimaryKeySelective(QltnMUniversity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_university
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int updateByPrimaryKey(QltnMUniversity record);
}