package vn.youthmanager.ict.common.db.model;

import java.util.Date;

public class QltnMDetailReport {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qltn_m_detail_report.DETAIL_REPORT_ID
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    private String detailReportId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qltn_m_detail_report.REPORT_ID
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    private String reportId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qltn_m_detail_report.DETAIL_REPORT_NAME
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    private String detailReportName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qltn_m_detail_report.CREATE_USER_ID
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    private String createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qltn_m_detail_report.CREATE_DATE
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qltn_m_detail_report.UPDATE_USER_ID
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    private String updateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qltn_m_detail_report.LAST_UPDATE_DATE
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    private Date lastUpdateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qltn_m_detail_report.DELETE_FLAG
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    private String deleteFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qltn_m_detail_report.DETAIL_REPORT_ID
     *
     * @return the value of qltn_m_detail_report.DETAIL_REPORT_ID
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    public String getDetailReportId() {
        return detailReportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qltn_m_detail_report.DETAIL_REPORT_ID
     *
     * @param detailReportId the value for qltn_m_detail_report.DETAIL_REPORT_ID
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    public void setDetailReportId(String detailReportId) {
        this.detailReportId = detailReportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qltn_m_detail_report.REPORT_ID
     *
     * @return the value of qltn_m_detail_report.REPORT_ID
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    public String getReportId() {
        return reportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qltn_m_detail_report.REPORT_ID
     *
     * @param reportId the value for qltn_m_detail_report.REPORT_ID
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    public void setReportId(String reportId) {
        this.reportId = reportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qltn_m_detail_report.DETAIL_REPORT_NAME
     *
     * @return the value of qltn_m_detail_report.DETAIL_REPORT_NAME
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    public String getDetailReportName() {
        return detailReportName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qltn_m_detail_report.DETAIL_REPORT_NAME
     *
     * @param detailReportName the value for qltn_m_detail_report.DETAIL_REPORT_NAME
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    public void setDetailReportName(String detailReportName) {
        this.detailReportName = detailReportName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qltn_m_detail_report.CREATE_USER_ID
     *
     * @return the value of qltn_m_detail_report.CREATE_USER_ID
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qltn_m_detail_report.CREATE_USER_ID
     *
     * @param createUserId the value for qltn_m_detail_report.CREATE_USER_ID
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qltn_m_detail_report.CREATE_DATE
     *
     * @return the value of qltn_m_detail_report.CREATE_DATE
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qltn_m_detail_report.CREATE_DATE
     *
     * @param createDate the value for qltn_m_detail_report.CREATE_DATE
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qltn_m_detail_report.UPDATE_USER_ID
     *
     * @return the value of qltn_m_detail_report.UPDATE_USER_ID
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    public String getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qltn_m_detail_report.UPDATE_USER_ID
     *
     * @param updateUserId the value for qltn_m_detail_report.UPDATE_USER_ID
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    public void setUpdateUserId(String updateUserId) {
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qltn_m_detail_report.LAST_UPDATE_DATE
     *
     * @return the value of qltn_m_detail_report.LAST_UPDATE_DATE
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qltn_m_detail_report.LAST_UPDATE_DATE
     *
     * @param lastUpdateDate the value for qltn_m_detail_report.LAST_UPDATE_DATE
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qltn_m_detail_report.DELETE_FLAG
     *
     * @return the value of qltn_m_detail_report.DELETE_FLAG
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    public String getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qltn_m_detail_report.DELETE_FLAG
     *
     * @param deleteFlag the value for qltn_m_detail_report.DELETE_FLAG
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    public void setDeleteFlag(String deleteFlag) {
        this.deleteFlag = deleteFlag;
    }
}