package vn.youthmanager.ict.common.db.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import vn.youthmanager.ict.common.db.model.QltnMTown;
import vn.youthmanager.ict.common.db.model.QltnMTownExample;

public interface QltnMTownMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_town
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int countByExample(QltnMTownExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_town
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int deleteByExample(QltnMTownExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_town
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int deleteByPrimaryKey(String townId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_town
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int insert(QltnMTown record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_town
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int insertSelective(QltnMTown record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_town
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    List<QltnMTown> selectByExample(QltnMTownExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_town
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    QltnMTown selectByPrimaryKey(String townId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_town
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int updateByExampleSelective(@Param("record") QltnMTown record, @Param("example") QltnMTownExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_town
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int updateByExample(@Param("record") QltnMTown record, @Param("example") QltnMTownExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_town
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int updateByPrimaryKeySelective(QltnMTown record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_town
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int updateByPrimaryKey(QltnMTown record);
}