package vn.youthmanager.ict.common.db.model;

public class QltnMProcessPersonKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qltn_m_process_person.PROCESS_PERSON_ID
     *
     * @mbggenerated Sun Jul 16 10:47:33 ICT 2017
     */
    private String processPersonId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qltn_m_process_person.PERSON_ID
     *
     * @mbggenerated Sun Jul 16 10:47:33 ICT 2017
     */
    private String personId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qltn_m_process_person.PROCESS_PERSON_ID
     *
     * @return the value of qltn_m_process_person.PROCESS_PERSON_ID
     *
     * @mbggenerated Sun Jul 16 10:47:33 ICT 2017
     */
    public String getProcessPersonId() {
        return processPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qltn_m_process_person.PROCESS_PERSON_ID
     *
     * @param processPersonId the value for qltn_m_process_person.PROCESS_PERSON_ID
     *
     * @mbggenerated Sun Jul 16 10:47:33 ICT 2017
     */
    public void setProcessPersonId(String processPersonId) {
        this.processPersonId = processPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qltn_m_process_person.PERSON_ID
     *
     * @return the value of qltn_m_process_person.PERSON_ID
     *
     * @mbggenerated Sun Jul 16 10:47:33 ICT 2017
     */
    public String getPersonId() {
        return personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qltn_m_process_person.PERSON_ID
     *
     * @param personId the value for qltn_m_process_person.PERSON_ID
     *
     * @mbggenerated Sun Jul 16 10:47:33 ICT 2017
     */
    public void setPersonId(String personId) {
        this.personId = personId;
    }
}