package vn.youthmanager.ict.common.db.model;

import java.util.Date;

public class QltnMFamilyRelatives {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qltn_m_family_relatives.FAMILY_PERSON_ID
     *
     * @mbggenerated Tue Jul 18 21:27:11 ICT 2017
     */
    private String familyPersonId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qltn_m_family_relatives.PERSON_ID
     *
     * @mbggenerated Tue Jul 18 21:27:11 ICT 2017
     */
    private String personId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qltn_m_family_relatives.RELATION
     *
     * @mbggenerated Tue Jul 18 21:27:11 ICT 2017
     */
    private String relation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qltn_m_family_relatives.STATUS
     *
     * @mbggenerated Tue Jul 18 21:27:11 ICT 2017
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qltn_m_family_relatives.BIRTH_DAY
     *
     * @mbggenerated Tue Jul 18 21:27:11 ICT 2017
     */
    private String birthDay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qltn_m_family_relatives.JOB
     *
     * @mbggenerated Tue Jul 18 21:27:11 ICT 2017
     */
    private String job;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qltn_m_family_relatives.WORK_PLACE
     *
     * @mbggenerated Tue Jul 18 21:27:11 ICT 2017
     */
    private String workPlace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qltn_m_family_relatives.NOTE
     *
     * @mbggenerated Tue Jul 18 21:27:11 ICT 2017
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qltn_m_family_relatives.CREATE_USER_ID
     *
     * @mbggenerated Tue Jul 18 21:27:11 ICT 2017
     */
    private String createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qltn_m_family_relatives.CREATE_DATE
     *
     * @mbggenerated Tue Jul 18 21:27:11 ICT 2017
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qltn_m_family_relatives.UPDATE_USER_ID
     *
     * @mbggenerated Tue Jul 18 21:27:11 ICT 2017
     */
    private String updateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qltn_m_family_relatives.LAST_UPDATE_DATE
     *
     * @mbggenerated Tue Jul 18 21:27:11 ICT 2017
     */
    private Date lastUpdateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qltn_m_family_relatives.DELETE_FLAG
     *
     * @mbggenerated Tue Jul 18 21:27:11 ICT 2017
     */
    private String deleteFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qltn_m_family_relatives.FAMILY_PERSON_ID
     *
     * @return the value of qltn_m_family_relatives.FAMILY_PERSON_ID
     *
     * @mbggenerated Tue Jul 18 21:27:11 ICT 2017
     */
    public String getFamilyPersonId() {
        return familyPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qltn_m_family_relatives.FAMILY_PERSON_ID
     *
     * @param familyPersonId the value for qltn_m_family_relatives.FAMILY_PERSON_ID
     *
     * @mbggenerated Tue Jul 18 21:27:11 ICT 2017
     */
    public void setFamilyPersonId(String familyPersonId) {
        this.familyPersonId = familyPersonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qltn_m_family_relatives.PERSON_ID
     *
     * @return the value of qltn_m_family_relatives.PERSON_ID
     *
     * @mbggenerated Tue Jul 18 21:27:11 ICT 2017
     */
    public String getPersonId() {
        return personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qltn_m_family_relatives.PERSON_ID
     *
     * @param personId the value for qltn_m_family_relatives.PERSON_ID
     *
     * @mbggenerated Tue Jul 18 21:27:11 ICT 2017
     */
    public void setPersonId(String personId) {
        this.personId = personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qltn_m_family_relatives.RELATION
     *
     * @return the value of qltn_m_family_relatives.RELATION
     *
     * @mbggenerated Tue Jul 18 21:27:11 ICT 2017
     */
    public String getRelation() {
        return relation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qltn_m_family_relatives.RELATION
     *
     * @param relation the value for qltn_m_family_relatives.RELATION
     *
     * @mbggenerated Tue Jul 18 21:27:11 ICT 2017
     */
    public void setRelation(String relation) {
        this.relation = relation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qltn_m_family_relatives.STATUS
     *
     * @return the value of qltn_m_family_relatives.STATUS
     *
     * @mbggenerated Tue Jul 18 21:27:11 ICT 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qltn_m_family_relatives.STATUS
     *
     * @param status the value for qltn_m_family_relatives.STATUS
     *
     * @mbggenerated Tue Jul 18 21:27:11 ICT 2017
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qltn_m_family_relatives.BIRTH_DAY
     *
     * @return the value of qltn_m_family_relatives.BIRTH_DAY
     *
     * @mbggenerated Tue Jul 18 21:27:11 ICT 2017
     */
    public String getBirthDay() {
        return birthDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qltn_m_family_relatives.BIRTH_DAY
     *
     * @param birthDay the value for qltn_m_family_relatives.BIRTH_DAY
     *
     * @mbggenerated Tue Jul 18 21:27:11 ICT 2017
     */
    public void setBirthDay(String birthDay) {
        this.birthDay = birthDay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qltn_m_family_relatives.JOB
     *
     * @return the value of qltn_m_family_relatives.JOB
     *
     * @mbggenerated Tue Jul 18 21:27:11 ICT 2017
     */
    public String getJob() {
        return job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qltn_m_family_relatives.JOB
     *
     * @param job the value for qltn_m_family_relatives.JOB
     *
     * @mbggenerated Tue Jul 18 21:27:11 ICT 2017
     */
    public void setJob(String job) {
        this.job = job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qltn_m_family_relatives.WORK_PLACE
     *
     * @return the value of qltn_m_family_relatives.WORK_PLACE
     *
     * @mbggenerated Tue Jul 18 21:27:11 ICT 2017
     */
    public String getWorkPlace() {
        return workPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qltn_m_family_relatives.WORK_PLACE
     *
     * @param workPlace the value for qltn_m_family_relatives.WORK_PLACE
     *
     * @mbggenerated Tue Jul 18 21:27:11 ICT 2017
     */
    public void setWorkPlace(String workPlace) {
        this.workPlace = workPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qltn_m_family_relatives.NOTE
     *
     * @return the value of qltn_m_family_relatives.NOTE
     *
     * @mbggenerated Tue Jul 18 21:27:11 ICT 2017
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qltn_m_family_relatives.NOTE
     *
     * @param note the value for qltn_m_family_relatives.NOTE
     *
     * @mbggenerated Tue Jul 18 21:27:11 ICT 2017
     */
    public void setNote(String note) {
        this.note = note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qltn_m_family_relatives.CREATE_USER_ID
     *
     * @return the value of qltn_m_family_relatives.CREATE_USER_ID
     *
     * @mbggenerated Tue Jul 18 21:27:11 ICT 2017
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qltn_m_family_relatives.CREATE_USER_ID
     *
     * @param createUserId the value for qltn_m_family_relatives.CREATE_USER_ID
     *
     * @mbggenerated Tue Jul 18 21:27:11 ICT 2017
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qltn_m_family_relatives.CREATE_DATE
     *
     * @return the value of qltn_m_family_relatives.CREATE_DATE
     *
     * @mbggenerated Tue Jul 18 21:27:11 ICT 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qltn_m_family_relatives.CREATE_DATE
     *
     * @param createDate the value for qltn_m_family_relatives.CREATE_DATE
     *
     * @mbggenerated Tue Jul 18 21:27:11 ICT 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qltn_m_family_relatives.UPDATE_USER_ID
     *
     * @return the value of qltn_m_family_relatives.UPDATE_USER_ID
     *
     * @mbggenerated Tue Jul 18 21:27:11 ICT 2017
     */
    public String getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qltn_m_family_relatives.UPDATE_USER_ID
     *
     * @param updateUserId the value for qltn_m_family_relatives.UPDATE_USER_ID
     *
     * @mbggenerated Tue Jul 18 21:27:11 ICT 2017
     */
    public void setUpdateUserId(String updateUserId) {
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qltn_m_family_relatives.LAST_UPDATE_DATE
     *
     * @return the value of qltn_m_family_relatives.LAST_UPDATE_DATE
     *
     * @mbggenerated Tue Jul 18 21:27:11 ICT 2017
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qltn_m_family_relatives.LAST_UPDATE_DATE
     *
     * @param lastUpdateDate the value for qltn_m_family_relatives.LAST_UPDATE_DATE
     *
     * @mbggenerated Tue Jul 18 21:27:11 ICT 2017
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qltn_m_family_relatives.DELETE_FLAG
     *
     * @return the value of qltn_m_family_relatives.DELETE_FLAG
     *
     * @mbggenerated Tue Jul 18 21:27:11 ICT 2017
     */
    public String getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qltn_m_family_relatives.DELETE_FLAG
     *
     * @param deleteFlag the value for qltn_m_family_relatives.DELETE_FLAG
     *
     * @mbggenerated Tue Jul 18 21:27:11 ICT 2017
     */
    public void setDeleteFlag(String deleteFlag) {
        this.deleteFlag = deleteFlag;
    }
}