package vn.youthmanager.ict.common.db.model;

import java.util.Date;

public class QltnMSignature {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qltn_m_signature.SIGNATURE_ID
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    private String signatureId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qltn_m_signature.SIGNATURE_NAME
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    private String signatureName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qltn_m_signature.CREATE_USER_ID
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    private String createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qltn_m_signature.CREATE_DATE
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qltn_m_signature.UPDATE_USER_ID
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    private String updateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qltn_m_signature.LAST_UPDATE_DATE
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    private Date lastUpdateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qltn_m_signature.DELETE_FLAG
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    private String deleteFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qltn_m_signature.SIGNATURE_ID
     *
     * @return the value of qltn_m_signature.SIGNATURE_ID
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    public String getSignatureId() {
        return signatureId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qltn_m_signature.SIGNATURE_ID
     *
     * @param signatureId the value for qltn_m_signature.SIGNATURE_ID
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    public void setSignatureId(String signatureId) {
        this.signatureId = signatureId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qltn_m_signature.SIGNATURE_NAME
     *
     * @return the value of qltn_m_signature.SIGNATURE_NAME
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    public String getSignatureName() {
        return signatureName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qltn_m_signature.SIGNATURE_NAME
     *
     * @param signatureName the value for qltn_m_signature.SIGNATURE_NAME
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    public void setSignatureName(String signatureName) {
        this.signatureName = signatureName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qltn_m_signature.CREATE_USER_ID
     *
     * @return the value of qltn_m_signature.CREATE_USER_ID
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qltn_m_signature.CREATE_USER_ID
     *
     * @param createUserId the value for qltn_m_signature.CREATE_USER_ID
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qltn_m_signature.CREATE_DATE
     *
     * @return the value of qltn_m_signature.CREATE_DATE
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qltn_m_signature.CREATE_DATE
     *
     * @param createDate the value for qltn_m_signature.CREATE_DATE
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qltn_m_signature.UPDATE_USER_ID
     *
     * @return the value of qltn_m_signature.UPDATE_USER_ID
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    public String getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qltn_m_signature.UPDATE_USER_ID
     *
     * @param updateUserId the value for qltn_m_signature.UPDATE_USER_ID
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    public void setUpdateUserId(String updateUserId) {
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qltn_m_signature.LAST_UPDATE_DATE
     *
     * @return the value of qltn_m_signature.LAST_UPDATE_DATE
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qltn_m_signature.LAST_UPDATE_DATE
     *
     * @param lastUpdateDate the value for qltn_m_signature.LAST_UPDATE_DATE
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qltn_m_signature.DELETE_FLAG
     *
     * @return the value of qltn_m_signature.DELETE_FLAG
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    public String getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qltn_m_signature.DELETE_FLAG
     *
     * @param deleteFlag the value for qltn_m_signature.DELETE_FLAG
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    public void setDeleteFlag(String deleteFlag) {
        this.deleteFlag = deleteFlag;
    }
}