package vn.youthmanager.ict.common.db.model;

import java.util.Date;

public class QltnMProcessPerson extends QltnMProcessPersonKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qltn_m_process_person.FROM_YEAR
     *
     * @mbggenerated Sun Jul 16 10:47:33 ICT 2017
     */
    private String fromYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qltn_m_process_person.TO_YEAR
     *
     * @mbggenerated Sun Jul 16 10:47:33 ICT 2017
     */
    private String toYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qltn_m_process_person.CONTENT
     *
     * @mbggenerated Sun Jul 16 10:47:33 ICT 2017
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qltn_m_process_person.CREATE_USER_ID
     *
     * @mbggenerated Sun Jul 16 10:47:33 ICT 2017
     */
    private String createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qltn_m_process_person.CREATE_DATE
     *
     * @mbggenerated Sun Jul 16 10:47:33 ICT 2017
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qltn_m_process_person.UPDATE_USER_ID
     *
     * @mbggenerated Sun Jul 16 10:47:33 ICT 2017
     */
    private String updateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qltn_m_process_person.LAST_UPDATE_DATE
     *
     * @mbggenerated Sun Jul 16 10:47:33 ICT 2017
     */
    private Date lastUpdateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qltn_m_process_person.DELETE_FLAG
     *
     * @mbggenerated Sun Jul 16 10:47:33 ICT 2017
     */
    private String deleteFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qltn_m_process_person.FROM_YEAR
     *
     * @return the value of qltn_m_process_person.FROM_YEAR
     *
     * @mbggenerated Sun Jul 16 10:47:33 ICT 2017
     */
    public String getFromYear() {
        return fromYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qltn_m_process_person.FROM_YEAR
     *
     * @param fromYear the value for qltn_m_process_person.FROM_YEAR
     *
     * @mbggenerated Sun Jul 16 10:47:33 ICT 2017
     */
    public void setFromYear(String fromYear) {
        this.fromYear = fromYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qltn_m_process_person.TO_YEAR
     *
     * @return the value of qltn_m_process_person.TO_YEAR
     *
     * @mbggenerated Sun Jul 16 10:47:33 ICT 2017
     */
    public String getToYear() {
        return toYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qltn_m_process_person.TO_YEAR
     *
     * @param toYear the value for qltn_m_process_person.TO_YEAR
     *
     * @mbggenerated Sun Jul 16 10:47:33 ICT 2017
     */
    public void setToYear(String toYear) {
        this.toYear = toYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qltn_m_process_person.CONTENT
     *
     * @return the value of qltn_m_process_person.CONTENT
     *
     * @mbggenerated Sun Jul 16 10:47:33 ICT 2017
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qltn_m_process_person.CONTENT
     *
     * @param content the value for qltn_m_process_person.CONTENT
     *
     * @mbggenerated Sun Jul 16 10:47:33 ICT 2017
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qltn_m_process_person.CREATE_USER_ID
     *
     * @return the value of qltn_m_process_person.CREATE_USER_ID
     *
     * @mbggenerated Sun Jul 16 10:47:33 ICT 2017
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qltn_m_process_person.CREATE_USER_ID
     *
     * @param createUserId the value for qltn_m_process_person.CREATE_USER_ID
     *
     * @mbggenerated Sun Jul 16 10:47:33 ICT 2017
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qltn_m_process_person.CREATE_DATE
     *
     * @return the value of qltn_m_process_person.CREATE_DATE
     *
     * @mbggenerated Sun Jul 16 10:47:33 ICT 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qltn_m_process_person.CREATE_DATE
     *
     * @param createDate the value for qltn_m_process_person.CREATE_DATE
     *
     * @mbggenerated Sun Jul 16 10:47:33 ICT 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qltn_m_process_person.UPDATE_USER_ID
     *
     * @return the value of qltn_m_process_person.UPDATE_USER_ID
     *
     * @mbggenerated Sun Jul 16 10:47:33 ICT 2017
     */
    public String getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qltn_m_process_person.UPDATE_USER_ID
     *
     * @param updateUserId the value for qltn_m_process_person.UPDATE_USER_ID
     *
     * @mbggenerated Sun Jul 16 10:47:33 ICT 2017
     */
    public void setUpdateUserId(String updateUserId) {
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qltn_m_process_person.LAST_UPDATE_DATE
     *
     * @return the value of qltn_m_process_person.LAST_UPDATE_DATE
     *
     * @mbggenerated Sun Jul 16 10:47:33 ICT 2017
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qltn_m_process_person.LAST_UPDATE_DATE
     *
     * @param lastUpdateDate the value for qltn_m_process_person.LAST_UPDATE_DATE
     *
     * @mbggenerated Sun Jul 16 10:47:33 ICT 2017
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qltn_m_process_person.DELETE_FLAG
     *
     * @return the value of qltn_m_process_person.DELETE_FLAG
     *
     * @mbggenerated Sun Jul 16 10:47:33 ICT 2017
     */
    public String getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qltn_m_process_person.DELETE_FLAG
     *
     * @param deleteFlag the value for qltn_m_process_person.DELETE_FLAG
     *
     * @mbggenerated Sun Jul 16 10:47:33 ICT 2017
     */
    public void setDeleteFlag(String deleteFlag) {
        this.deleteFlag = deleteFlag;
    }
}