package vn.youthmanager.ict.common.db.model;

public class QltnMNoteReportKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qltn_m_note_report.NOTE_REPORT_ID
     *
     * @mbggenerated Wed Jun 28 16:03:39 ICT 2017
     */
    private String noteReportId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qltn_m_note_report.REPORT_ID
     *
     * @mbggenerated Wed Jun 28 16:03:39 ICT 2017
     */
    private String reportId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qltn_m_note_report.DETAIL_REPORT_ID
     *
     * @mbggenerated Wed Jun 28 16:03:39 ICT 2017
     */
    private String detailReportId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qltn_m_note_report.PERSON_ID
     *
     * @mbggenerated Wed Jun 28 16:03:39 ICT 2017
     */
    private String personId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qltn_m_note_report.NOTE_REPORT_ID
     *
     * @return the value of qltn_m_note_report.NOTE_REPORT_ID
     *
     * @mbggenerated Wed Jun 28 16:03:39 ICT 2017
     */
    public String getNoteReportId() {
        return noteReportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qltn_m_note_report.NOTE_REPORT_ID
     *
     * @param noteReportId the value for qltn_m_note_report.NOTE_REPORT_ID
     *
     * @mbggenerated Wed Jun 28 16:03:39 ICT 2017
     */
    public void setNoteReportId(String noteReportId) {
        this.noteReportId = noteReportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qltn_m_note_report.REPORT_ID
     *
     * @return the value of qltn_m_note_report.REPORT_ID
     *
     * @mbggenerated Wed Jun 28 16:03:39 ICT 2017
     */
    public String getReportId() {
        return reportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qltn_m_note_report.REPORT_ID
     *
     * @param reportId the value for qltn_m_note_report.REPORT_ID
     *
     * @mbggenerated Wed Jun 28 16:03:39 ICT 2017
     */
    public void setReportId(String reportId) {
        this.reportId = reportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qltn_m_note_report.DETAIL_REPORT_ID
     *
     * @return the value of qltn_m_note_report.DETAIL_REPORT_ID
     *
     * @mbggenerated Wed Jun 28 16:03:39 ICT 2017
     */
    public String getDetailReportId() {
        return detailReportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qltn_m_note_report.DETAIL_REPORT_ID
     *
     * @param detailReportId the value for qltn_m_note_report.DETAIL_REPORT_ID
     *
     * @mbggenerated Wed Jun 28 16:03:39 ICT 2017
     */
    public void setDetailReportId(String detailReportId) {
        this.detailReportId = detailReportId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qltn_m_note_report.PERSON_ID
     *
     * @return the value of qltn_m_note_report.PERSON_ID
     *
     * @mbggenerated Wed Jun 28 16:03:39 ICT 2017
     */
    public String getPersonId() {
        return personId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qltn_m_note_report.PERSON_ID
     *
     * @param personId the value for qltn_m_note_report.PERSON_ID
     *
     * @mbggenerated Wed Jun 28 16:03:39 ICT 2017
     */
    public void setPersonId(String personId) {
        this.personId = personId;
    }
}