package vn.youthmanager.ict.common.db.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import vn.youthmanager.ict.common.db.model.QltnMEducational;
import vn.youthmanager.ict.common.db.model.QltnMEducationalExample;

public interface QltnMEducationalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_educational
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int countByExample(QltnMEducationalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_educational
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int deleteByExample(QltnMEducationalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_educational
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int deleteByPrimaryKey(String educationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_educational
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int insert(QltnMEducational record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_educational
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int insertSelective(QltnMEducational record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_educational
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    List<QltnMEducational> selectByExample(QltnMEducationalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_educational
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    QltnMEducational selectByPrimaryKey(String educationId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_educational
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int updateByExampleSelective(@Param("record") QltnMEducational record, @Param("example") QltnMEducationalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_educational
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int updateByExample(@Param("record") QltnMEducational record, @Param("example") QltnMEducationalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_educational
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int updateByPrimaryKeySelective(QltnMEducational record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_educational
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int updateByPrimaryKey(QltnMEducational record);
}