package vn.youthmanager.ict.common.db.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import vn.youthmanager.ict.common.db.model.QltnMUsers;
import vn.youthmanager.ict.common.db.model.QltnMUsersExample;

public interface QltnMUsersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_users
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int countByExample(QltnMUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_users
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int deleteByExample(QltnMUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_users
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int deleteByPrimaryKey(String usersId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_users
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int insert(QltnMUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_users
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int insertSelective(QltnMUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_users
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    List<QltnMUsers> selectByExample(QltnMUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_users
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    QltnMUsers selectByPrimaryKey(String usersId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_users
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int updateByExampleSelective(@Param("record") QltnMUsers record, @Param("example") QltnMUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_users
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int updateByExample(@Param("record") QltnMUsers record, @Param("example") QltnMUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_users
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int updateByPrimaryKeySelective(QltnMUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_users
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int updateByPrimaryKey(QltnMUsers record);
}