package vn.youthmanager.ict.common.db.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import vn.youthmanager.ict.common.db.model.QltnMScreen;
import vn.youthmanager.ict.common.db.model.QltnMScreenExample;

public interface QltnMScreenMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_screen
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int countByExample(QltnMScreenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_screen
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int deleteByExample(QltnMScreenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_screen
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int deleteByPrimaryKey(String screenId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_screen
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int insert(QltnMScreen record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_screen
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int insertSelective(QltnMScreen record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_screen
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    List<QltnMScreen> selectByExample(QltnMScreenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_screen
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    QltnMScreen selectByPrimaryKey(String screenId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_screen
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int updateByExampleSelective(@Param("record") QltnMScreen record, @Param("example") QltnMScreenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_screen
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int updateByExample(@Param("record") QltnMScreen record, @Param("example") QltnMScreenExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_screen
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int updateByPrimaryKeySelective(QltnMScreen record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_screen
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int updateByPrimaryKey(QltnMScreen record);
}