package vn.youthmanager.ict.common.db.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import vn.youthmanager.ict.common.db.model.QltnMDetailReport;
import vn.youthmanager.ict.common.db.model.QltnMDetailReportExample;

public interface QltnMDetailReportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_detail_report
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int countByExample(QltnMDetailReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_detail_report
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int deleteByExample(QltnMDetailReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_detail_report
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int deleteByPrimaryKey(String detailReportId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_detail_report
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int insert(QltnMDetailReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_detail_report
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int insertSelective(QltnMDetailReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_detail_report
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    List<QltnMDetailReport> selectByExample(QltnMDetailReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_detail_report
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    QltnMDetailReport selectByPrimaryKey(String detailReportId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_detail_report
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int updateByExampleSelective(@Param("record") QltnMDetailReport record, @Param("example") QltnMDetailReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_detail_report
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int updateByExample(@Param("record") QltnMDetailReport record, @Param("example") QltnMDetailReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_detail_report
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int updateByPrimaryKeySelective(QltnMDetailReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_detail_report
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int updateByPrimaryKey(QltnMDetailReport record);
}