package vn.youthmanager.ict.common.db.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import vn.youthmanager.ict.common.db.model.QltnMSignature;
import vn.youthmanager.ict.common.db.model.QltnMSignatureExample;

public interface QltnMSignatureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_signature
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int countByExample(QltnMSignatureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_signature
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int deleteByExample(QltnMSignatureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_signature
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int deleteByPrimaryKey(String signatureId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_signature
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int insert(QltnMSignature record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_signature
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int insertSelective(QltnMSignature record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_signature
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    List<QltnMSignature> selectByExample(QltnMSignatureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_signature
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    QltnMSignature selectByPrimaryKey(String signatureId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_signature
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int updateByExampleSelective(@Param("record") QltnMSignature record, @Param("example") QltnMSignatureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_signature
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int updateByExample(@Param("record") QltnMSignature record, @Param("example") QltnMSignatureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_signature
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int updateByPrimaryKeySelective(QltnMSignature record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_signature
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int updateByPrimaryKey(QltnMSignature record);
}