package vn.youthmanager.ict.common.db.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import vn.youthmanager.ict.common.db.model.QltnMAccessAuthorization;
import vn.youthmanager.ict.common.db.model.QltnMAccessAuthorizationExample;
import vn.youthmanager.ict.common.db.model.QltnMAccessAuthorizationKey;

public interface QltnMAccessAuthorizationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_access_authorization
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int countByExample(QltnMAccessAuthorizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_access_authorization
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int deleteByExample(QltnMAccessAuthorizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_access_authorization
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int deleteByPrimaryKey(QltnMAccessAuthorizationKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_access_authorization
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int insert(QltnMAccessAuthorization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_access_authorization
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int insertSelective(QltnMAccessAuthorization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_access_authorization
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    List<QltnMAccessAuthorization> selectByExample(QltnMAccessAuthorizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_access_authorization
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    QltnMAccessAuthorization selectByPrimaryKey(QltnMAccessAuthorizationKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_access_authorization
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int updateByExampleSelective(@Param("record") QltnMAccessAuthorization record, @Param("example") QltnMAccessAuthorizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_access_authorization
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int updateByExample(@Param("record") QltnMAccessAuthorization record, @Param("example") QltnMAccessAuthorizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_access_authorization
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int updateByPrimaryKeySelective(QltnMAccessAuthorization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_access_authorization
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int updateByPrimaryKey(QltnMAccessAuthorization record);
}