package vn.youthmanager.ict.common.db.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import vn.youthmanager.ict.common.db.model.QltnMAuthorization;
import vn.youthmanager.ict.common.db.model.QltnMAuthorizationExample;

public interface QltnMAuthorizationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_authorization
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int countByExample(QltnMAuthorizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_authorization
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int deleteByExample(QltnMAuthorizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_authorization
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int deleteByPrimaryKey(String authorizationTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_authorization
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int insert(QltnMAuthorization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_authorization
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int insertSelective(QltnMAuthorization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_authorization
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    List<QltnMAuthorization> selectByExample(QltnMAuthorizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_authorization
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    QltnMAuthorization selectByPrimaryKey(String authorizationTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_authorization
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int updateByExampleSelective(@Param("record") QltnMAuthorization record, @Param("example") QltnMAuthorizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_authorization
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int updateByExample(@Param("record") QltnMAuthorization record, @Param("example") QltnMAuthorizationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_authorization
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int updateByPrimaryKeySelective(QltnMAuthorization record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_authorization
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int updateByPrimaryKey(QltnMAuthorization record);
}