package vn.youthmanager.ict.common.db.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import vn.youthmanager.ict.common.db.model.QltnMGroups;
import vn.youthmanager.ict.common.db.model.QltnMGroupsExample;

public interface QltnMGroupsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_groups
     *
     * @mbggenerated Sat Apr 29 13:21:11 ICT 2017
     */
    int countByExample(QltnMGroupsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_groups
     *
     * @mbggenerated Sat Apr 29 13:21:11 ICT 2017
     */
    int deleteByExample(QltnMGroupsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_groups
     *
     * @mbggenerated Sat Apr 29 13:21:11 ICT 2017
     */
    int deleteByPrimaryKey(String groupsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_groups
     *
     * @mbggenerated Sat Apr 29 13:21:11 ICT 2017
     */
    int insert(QltnMGroups record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_groups
     *
     * @mbggenerated Sat Apr 29 13:21:11 ICT 2017
     */
    int insertSelective(QltnMGroups record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_groups
     *
     * @mbggenerated Sat Apr 29 13:21:11 ICT 2017
     */
    List<QltnMGroups> selectByExample(QltnMGroupsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_groups
     *
     * @mbggenerated Sat Apr 29 13:21:11 ICT 2017
     */
    QltnMGroups selectByPrimaryKey(String groupsId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_groups
     *
     * @mbggenerated Sat Apr 29 13:21:11 ICT 2017
     */
    int updateByExampleSelective(@Param("record") QltnMGroups record, @Param("example") QltnMGroupsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_groups
     *
     * @mbggenerated Sat Apr 29 13:21:11 ICT 2017
     */
    int updateByExample(@Param("record") QltnMGroups record, @Param("example") QltnMGroupsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_groups
     *
     * @mbggenerated Sat Apr 29 13:21:11 ICT 2017
     */
    int updateByPrimaryKeySelective(QltnMGroups record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_groups
     *
     * @mbggenerated Sat Apr 29 13:21:11 ICT 2017
     */
    int updateByPrimaryKey(QltnMGroups record);
}