package vn.youthmanager.ict.common.db.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import vn.youthmanager.ict.common.db.model.QltnMCity;
import vn.youthmanager.ict.common.db.model.QltnMCityExample;

public interface QltnMCityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_city
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int countByExample(QltnMCityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_city
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int deleteByExample(QltnMCityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_city
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int deleteByPrimaryKey(String cityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_city
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int insert(QltnMCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_city
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int insertSelective(QltnMCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_city
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    List<QltnMCity> selectByExample(QltnMCityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_city
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    QltnMCity selectByPrimaryKey(String cityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_city
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int updateByExampleSelective(@Param("record") QltnMCity record, @Param("example") QltnMCityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_city
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int updateByExample(@Param("record") QltnMCity record, @Param("example") QltnMCityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_city
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int updateByPrimaryKeySelective(QltnMCity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_city
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int updateByPrimaryKey(QltnMCity record);
}