package vn.youthmanager.ict.common.db.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import vn.youthmanager.ict.common.db.model.QltnMReport;
import vn.youthmanager.ict.common.db.model.QltnMReportExample;

public interface QltnMReportMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_report
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int countByExample(QltnMReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_report
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int deleteByExample(QltnMReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_report
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int deleteByPrimaryKey(String reportId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_report
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int insert(QltnMReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_report
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int insertSelective(QltnMReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_report
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    List<QltnMReport> selectByExample(QltnMReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_report
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    QltnMReport selectByPrimaryKey(String reportId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_report
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int updateByExampleSelective(@Param("record") QltnMReport record, @Param("example") QltnMReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_report
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int updateByExample(@Param("record") QltnMReport record, @Param("example") QltnMReportExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_report
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int updateByPrimaryKeySelective(QltnMReport record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_report
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int updateByPrimaryKey(QltnMReport record);
}