package vn.youthmanager.ict.common.db.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import vn.youthmanager.ict.common.db.model.QltnMDistrict;
import vn.youthmanager.ict.common.db.model.QltnMDistrictExample;

public interface QltnMDistrictMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_district
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int countByExample(QltnMDistrictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_district
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int deleteByExample(QltnMDistrictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_district
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int deleteByPrimaryKey(String districtId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_district
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int insert(QltnMDistrict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_district
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int insertSelective(QltnMDistrict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_district
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    List<QltnMDistrict> selectByExample(QltnMDistrictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_district
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    QltnMDistrict selectByPrimaryKey(String districtId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_district
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int updateByExampleSelective(@Param("record") QltnMDistrict record, @Param("example") QltnMDistrictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_district
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int updateByExample(@Param("record") QltnMDistrict record, @Param("example") QltnMDistrictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_district
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int updateByPrimaryKeySelective(QltnMDistrict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_district
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int updateByPrimaryKey(QltnMDistrict record);
}