package vn.youthmanager.ict.common.db.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import vn.youthmanager.ict.common.db.model.QltnMProcessPerson;
import vn.youthmanager.ict.common.db.model.QltnMProcessPersonExample;
import vn.youthmanager.ict.common.db.model.QltnMProcessPersonKey;

public interface QltnMProcessPersonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_process_person
     *
     * @mbggenerated Sun Jul 16 10:47:33 ICT 2017
     */
    int countByExample(QltnMProcessPersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_process_person
     *
     * @mbggenerated Sun Jul 16 10:47:33 ICT 2017
     */
    int deleteByExample(QltnMProcessPersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_process_person
     *
     * @mbggenerated Sun Jul 16 10:47:33 ICT 2017
     */
    int deleteByPrimaryKey(QltnMProcessPersonKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_process_person
     *
     * @mbggenerated Sun Jul 16 10:47:33 ICT 2017
     */
    int insert(QltnMProcessPerson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_process_person
     *
     * @mbggenerated Sun Jul 16 10:47:33 ICT 2017
     */
    int insertSelective(QltnMProcessPerson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_process_person
     *
     * @mbggenerated Sun Jul 16 10:47:33 ICT 2017
     */
    List<QltnMProcessPerson> selectByExample(QltnMProcessPersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_process_person
     *
     * @mbggenerated Sun Jul 16 10:47:33 ICT 2017
     */
    QltnMProcessPerson selectByPrimaryKey(QltnMProcessPersonKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_process_person
     *
     * @mbggenerated Sun Jul 16 10:47:33 ICT 2017
     */
    int updateByExampleSelective(@Param("record") QltnMProcessPerson record, @Param("example") QltnMProcessPersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_process_person
     *
     * @mbggenerated Sun Jul 16 10:47:33 ICT 2017
     */
    int updateByExample(@Param("record") QltnMProcessPerson record, @Param("example") QltnMProcessPersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_process_person
     *
     * @mbggenerated Sun Jul 16 10:47:33 ICT 2017
     */
    int updateByPrimaryKeySelective(QltnMProcessPerson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_process_person
     *
     * @mbggenerated Sun Jul 16 10:47:33 ICT 2017
     */
    int updateByPrimaryKey(QltnMProcessPerson record);
}