package vn.youthmanager.ict.common.db.model;

import java.util.Date;

public class QltnMUsers {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qltn_m_users.USERS_ID
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    private String usersId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qltn_m_users.USERS_NAME
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    private String usersName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qltn_m_users.PASSWORD
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qltn_m_users.AUTHORIZATION_TYPE_ID
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    private Integer authorizationTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qltn_m_users.CREATE_USER_ID
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    private String createUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qltn_m_users.CREATE_DATE
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qltn_m_users.UPDATE_USER_ID
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    private String updateUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qltn_m_users.LAST_UPDATE_DATE
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    private Date lastUpdateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column qltn_m_users.DELETE_FLAG
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    private String deleteFlag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qltn_m_users.USERS_ID
     *
     * @return the value of qltn_m_users.USERS_ID
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    public String getUsersId() {
        return usersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qltn_m_users.USERS_ID
     *
     * @param usersId the value for qltn_m_users.USERS_ID
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    public void setUsersId(String usersId) {
        this.usersId = usersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qltn_m_users.USERS_NAME
     *
     * @return the value of qltn_m_users.USERS_NAME
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    public String getUsersName() {
        return usersName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qltn_m_users.USERS_NAME
     *
     * @param usersName the value for qltn_m_users.USERS_NAME
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    public void setUsersName(String usersName) {
        this.usersName = usersName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qltn_m_users.PASSWORD
     *
     * @return the value of qltn_m_users.PASSWORD
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qltn_m_users.PASSWORD
     *
     * @param password the value for qltn_m_users.PASSWORD
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qltn_m_users.AUTHORIZATION_TYPE_ID
     *
     * @return the value of qltn_m_users.AUTHORIZATION_TYPE_ID
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    public Integer getAuthorizationTypeId() {
        return authorizationTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qltn_m_users.AUTHORIZATION_TYPE_ID
     *
     * @param authorizationTypeId the value for qltn_m_users.AUTHORIZATION_TYPE_ID
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    public void setAuthorizationTypeId(Integer authorizationTypeId) {
        this.authorizationTypeId = authorizationTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qltn_m_users.CREATE_USER_ID
     *
     * @return the value of qltn_m_users.CREATE_USER_ID
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qltn_m_users.CREATE_USER_ID
     *
     * @param createUserId the value for qltn_m_users.CREATE_USER_ID
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qltn_m_users.CREATE_DATE
     *
     * @return the value of qltn_m_users.CREATE_DATE
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qltn_m_users.CREATE_DATE
     *
     * @param createDate the value for qltn_m_users.CREATE_DATE
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qltn_m_users.UPDATE_USER_ID
     *
     * @return the value of qltn_m_users.UPDATE_USER_ID
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    public String getUpdateUserId() {
        return updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qltn_m_users.UPDATE_USER_ID
     *
     * @param updateUserId the value for qltn_m_users.UPDATE_USER_ID
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    public void setUpdateUserId(String updateUserId) {
        this.updateUserId = updateUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qltn_m_users.LAST_UPDATE_DATE
     *
     * @return the value of qltn_m_users.LAST_UPDATE_DATE
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    public Date getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qltn_m_users.LAST_UPDATE_DATE
     *
     * @param lastUpdateDate the value for qltn_m_users.LAST_UPDATE_DATE
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    public void setLastUpdateDate(Date lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column qltn_m_users.DELETE_FLAG
     *
     * @return the value of qltn_m_users.DELETE_FLAG
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    public String getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column qltn_m_users.DELETE_FLAG
     *
     * @param deleteFlag the value for qltn_m_users.DELETE_FLAG
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    public void setDeleteFlag(String deleteFlag) {
        this.deleteFlag = deleteFlag;
    }
}