package vn.youthmanager.ict.common.db.mapper;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import vn.youthmanager.ict.common.db.model.QltnMLocal;
import vn.youthmanager.ict.common.db.model.QltnMLocalExample;

public interface QltnMLocalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_local
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int countByExample(QltnMLocalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_local
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int deleteByExample(QltnMLocalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_local
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int deleteByPrimaryKey(String localId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_local
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int insert(QltnMLocal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_local
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int insertSelective(QltnMLocal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_local
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    List<QltnMLocal> selectByExample(QltnMLocalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_local
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    QltnMLocal selectByPrimaryKey(String localId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_local
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int updateByExampleSelective(@Param("record") QltnMLocal record, @Param("example") QltnMLocalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_local
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int updateByExample(@Param("record") QltnMLocal record, @Param("example") QltnMLocalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_local
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int updateByPrimaryKeySelective(QltnMLocal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table qltn_m_local
     *
     * @mbggenerated Sat Apr 08 18:31:52 ICT 2017
     */
    int updateByPrimaryKey(QltnMLocal record);
}